apiVersion: argoproj.io/v1alpha1
kind: AppProject
metadata:
  name: gitops-platform
  namespace: argocd
spec:
  description: Central GitOps control plane project
  sourceRepos:
    - "https://github.com/Learner-Gitops/control-plane.git"
  destinations:
    - namespace: production
      server: https://kubernetes.default.svc
    - namespace: staging
      server: https://kubernetes.default.svc
  clusterResourceWhitelist:
    - group: ""
      kind: Namespace
  namespaceResourceWhitelist:
    - group: "apps"
      kind: Deployment
    - group: ""
      kind: Service
    - group: ""
      kind: ConfigMap
