apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: staging-app
  namespace: argocd
spec:
  project: gitops-platform
  source:
    repoURL: https://github.com/Learner-Gitops/control-plane.git
    targetRevision: main
    path: gitops-control-plane/apps/staging
  destination:
    server: https://kubernetes.default.svc
    namespace: staging
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
